env:
  TERM: "xterm"

steps:
  - label: ":cypress: Cypress"
    command: ./ops/e2e.sh
    if: build.branch != 'master'

  - block: "Lauch Prod"
    branches: "master"

  - label: ":rocket: Deploy to Cloudfront"
    command: ./ops/show_environment.sh 
    branches: "master" 
