steps:
- label: ":pipeline:"
  command: ./ops/generate-steps-from-env-var.sh | buildkite-agent pipeline upload
  env:
    STEPS_COUNT: 2
- wait

- label: ":desktop_computer:"
  command: ./ops/fetch-and-display-number.sh collect