env:
  TERM: "xterm"

steps:
  - name: ":cypress: Cypress"
    command: ./ops/e2e.sh

  - block: "Lauch Prod"
    branches: "master"

  - name: ":rocket: Deploy to Cloudfront"
    command: ./ops/e2e.sh 
    branches: "master" 
