steps:
- label: ":pipeline:"
  command: ./ops/generate-steps-from-env-var.sh | buildkite-agent pipeline upload

- wait

- label: ":desktop_computer:"
  command: ./ops/fetch-and-display-number.sh collect